---
- name: Install docker and docker compose
  hosts: aws
  gather_facts: true
  become: yes

  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
      become: yes

    - name: Install system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      become: yes

    - name: Add the docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      become: yes

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
      become: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      become: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 0755
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 5

    - name: Verify the downloaded file
      stat:
        path: /usr/local/bin/docker-compose
      register: file_stat
      until: file_stat.stat.exists
      retries: 3
      delay: 5

    - name: Display Docker Compose version
      command: docker-compose --version
      changed_when: false
      register: compose_version

    - name: Create directory for docker-compose.yml
      file:
        path: /etc/minecraft-compose
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy docker-compose.yml
      copy:
        content: |
          version: "3.8"

          services:
            minecraft-bedrock-server:
              image: itzg/minecraft-bedrock-server
              container_name: minecraft-bedrock
              restart: unless-stopped
              ports:
                - "19132:19132/udp"
              volumes:
                - /etc/minecraft-compose/data:/data
              environment:
                EULA: "TRUE"
                SERVER_NAME: "Blakes Server"
                ALLOW_CHEATS: "false"
                MAX_PLAYERS: "20"
                VIEW_DISTANCE: "32"
                ONLINE_MODE: "true"
                SERVER_PORT: "19132"
        dest: /etc/minecraft-compose/docker-compose.yml
        owner: root
        group: root
        mode: "0644"
      notify: Run Docker Compose

    - name: Display installation status
      debug:
        msg: "Docker Compose {{ compose_version.stdout }} is installed successfully."

  handlers:
    - name: Run Docker Compose
      command: docker-compose -f /etc/minecraft-compose/docker-compose.yml up -d
      become: yes
